### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by pranjaldhole** [yapic/yapic#38]
yapic dependency: bigtiff has `mmap` dependency which supposedly makes yapic unix-only as `mmap` is unsupported on windows machines.

## Todo

- [x] List any other dependencies that makes yapic unsupported on windows machines.
- [x] List possible ways to remove this dependency in this issue.
- [x] Change this functionality so that yapic can be used across all platforms.
- [x] Resolve first in `yapic_io`
    + Resolved by https://github.com/yapic/yapic/issues/38#issuecomment-866807022

**Comment by pranjaldhole** [comment]
The [tifffile](https://pypi.org/project/tifffile/) package might be able to replace the bigtiff package dependency (possibly the only cause of yapic installation breaking in Windows systems). This should, in principle, resolve the _windows only_ problem.

**Comment by dlesmesl** [comment]
I know @mirindi95 has been working lately with YAPiC and our napari io plugin and I believe he implemented himself an alternative to the mmap, he created an issue in yapic_io which could also help [yapic_io issue](https://github.com/yapic/yapic_io/issues/20)

**Comment by cmohl2013** [comment]
Best would be, indeed, to replace bigtiff package by a well maintained standard tif library. 
We have special needs that were not supported by other tiff libraries at that time. That is why Manuel implemented the custom bigtiff library. The special needs are still there, and we have to look for a library that fulfills these needs:

* Multichannel and z-stack support
* Reading single tiles without importing the whole file into memory.
* In prediction mode: Writing single tiles to existing file without the need to import the whole file into memory.

**Comment by cmohl2013** [comment]
There is also a memmap implementation in tifffile:
https://github.com/cgohlke/tifffile/blob/991b450cb66f6cf9841af088e4792ce37260976e/tifffile/tifffile.py#L489

I could try to replace bigtiff memmap with tifffile memmap. In particular, this method in `yapic_io.tiffconnector` has to be adapted: 
https://github.com/yapic/yapic_io/blob/90900c741d22def5fe3d7099bd9bc8b688e8080d/yapic_io/tiff_connector.py#L251

**Comment by dlesmesl** [comment]
I worked on the transition from `bigtiff` to `Tifffile` this Wednesday, the dependencies used in `yapic_io` are `Tiff.write`, `PlaceHolder`, and `Tiff.memmap_tcz`. I already have a `TiffConnector` draft class using only `Tifffile` because this package has functions to do all the three `bigtiff` tasks but I haven't pushed it because I would like to run the tests first. 

I can push it in my fork so you could take a look.

**Comment by dlesmesl** [comment]
@cmohl2013 here you can take a look at the [Tifffile branch](https://github.com/dlesmesl/yapic_io/tree/Tifffile) so far I only commented the lines using `bigtiff` and added the `Tifffile` counterpart. The only modified file is [tiff_connector.py](https://github.com/dlesmesl/yapic_io/blob/Tifffile/yapic_io/tiff_connector.py). Please let me know if you have any comments!

**Comment by cmohl2013** [comment]
@dlesmesl I had a quick look on your changes in tiffconnector. Looks good so far. If you want you can make a pull request and we see if the tests pass. You may remove already the commented code.  I am happy to review the pull request.

**Comment by dlesmesl** [comment]
@cmohl2013 Thanks for the feedback! I haven been checking the tests and sadly some of them are not working, in the case of `TestTiffConnector` there is an error trying to initialize a connector with `test_data/tiffconnector_1/im/*.tif` and `test_data/tiffconnector_1/labels/*.tif`; the instance it's not being initialized because the dimensions between the images and labels don't match.

I wanted to ask how is normally the array dimension distribution of label tiff files, so far I have been working with only napari labels so I am not familiar on how to generate those tiff files labels.

**Comment by dlesmesl** [comment]
After working a bit more in this issue, there is something I don't have very clear with tiff files. Let's take for instance these tiff images in the zip file: [tifffile_test.zip](https://github.com/yapic/yapic/files/6465979/tifffile_test.zip)

The zip has 3 different images with the following dimension shapes:

1. `leaves_stack.tif`
   -  x = 790
   - y = 790
   - z = 7
   - c = 3 (channel)
2. `1000width_992height_4channels_16bit.tif`
   - x = 1000
   - y = 992
   - z = 1
   - c = 4
3. `40width26height3slices_rgb.tif`
   - x = 40
   - y = 26
   - z = 3
   - c = 2

The expected behavior when reading a tiff file (using `tifffile.memmap`) is to get a shape with the form of `(z, x, y, c)`, this occurs normally with `leaves_tack.tif` &#8594; `(7, 790, 790, 3)`. However this is not the case with the other two images, the resulting shapes are:

1. `1000width_992height_4channels_16bit.tif` &#8594; `(4, 992, 1000) = (c, y, x)`
2. `40width26height3slices_rgb.tif` &#8594; `(3, 2, 26, 40) = (z, c, y, x)`

What I initially did to solve the first `tifffile.memmap` difference with respect to `bigtiff` was to manually expand all the inputs to 4 dimensions using `numpy.expand_dims` (assuming that any image of 3 dimension would require to expand the z dimension and labels "have no channels"). This is not the most efficient solution because is not the general scenario.

On the other hand, each image have a different "dimension distribution" as we see with the examples. That is normally not a problem when uploading images to Napari for instance or even using `bigtiff,` but it is indeed a problem with `tifffile.memmap`.

The `tifffile.memmap` documentation has in the [docstring](https://github.com/cgohlke/tifffile/blob/991b450cb66f6cf9841af088e4792ce37260976e/tifffile/tifffile.py#L872):

>  Memory-mapping requires data stored in native byte order, without tiling,
    compression, predictors, etc.

I really don't know how tiling, compression, etc. affect the reading of `tifffile.memmap` but I think that might be the reason. I still haven't found for a detailed explanation of these tiff file manipulation on the web so I was wondering if maybe you know a start-point where I could start searching or if you have any suggestions on what I have done so far.

you can take a look that the code in my [fork](https://github.com/dlesmesl/yapic_io) (tiffile branch) which has some comments in the code, specially in `exp_dims` and `_open_label_file`.

**Comment by cmohl2013** [comment]
@dlesmesl 

I remember that the dimension order was quite tricky and changed, depending on the image type (multi z, multichannel, RGB...). All images of the test dataset are saved with ImageJ (Fiji in particular). ImageJ adds certain header information to the tif file. I am not sure, but it is likely that this header information contains the dimension order.

You may try the following: use `tiffile.memmap` with imagej option:
`memmap(path, imagej=True)`

I am not sure if it works, but maybe it makes dimension order consistent.

**Comment by dlesmesl** [comment]
Hello everyone,

There is a new version of yapic_io replacing bigtiff with tifffile. This might solve the issue in theory but there are still no tests in windows.

I already tested in Ubuntu and it's working fine. It wasn't necessary to delete the CellVoy connector, so it can be resumed in the future if desired.

**Comment by cmohl2013** [comment]
No problem, I will add a windows build in the travis jobs for yapic_io. Once this passes we can update yapic_io version and deploy to pip, then update yapic_io dependency in yapic.

**Comment by pranjaldhole** [comment]
Successful Windows build in `yapic_io` [https://github.com/yapic/yapic_io/pull/24](https://github.com/yapic/yapic_io/pull/24)
Dependency resolved!
